export const WORKER_CONTRACT_ADDRESS = "";
export const TOKEN_CONTRACT_ADDRESS = "";
export const BUSINESSES_CONTRACT_ADDRESS = "";
export const STAKING_CONTRACT_ADDRESS = "";

export const ACCOUNT_FACTORY_CONTRACT_ADDRESS = "";